dataset_name: "ecoli70"
type: "continuous"
n_nodes: 46

model:
    n_fourier_layers : 1

evaluation:
    ordering_batch_size : 1000
    eval_batch_size : 1000
    n_votes : 3
    t_max : 0.1 
    masking : True
    residue : True
    random_sampling : True
