setup:
    experiment_name : _scino_sachs_nocycle
    use_wandb : True
    save_folder : 'ckpt'
    output_path : "results_sachs_nocycle.txt"

datasets:
    name : sachs_nocycle
    n_nodes : [8] 
    num_graphs_list : [1]
    num_samples : 7466
    data_ver : 1

model:
    beta_0 : 0.0001
    beta_1 : 0.02
    T : 1
    hidden_channel : 1
    n_fourier_layers : 1
    norm_type : "batch"
    bias : False

training:
    model_save : True
    epochs : 1000
    batch_size : 1000
    learning_rate : 0.00005
    early_stopping_wait : 300
    T : 0.5
    scheduler: "plateau"
    mmd_model : False

evaluation:
    load_order : True
    ordering_batch_size : 1000
    eval_batch_size : 500
    n_votes : 3
    t_max : 1
    masking : True
    residue : True
    pruning_P : False
    cutoff : 0.001
    random_sampling : False
