setup:
    experiment_name : _fno_n100
    use_wandb : True
    save_folder : 'ckpt'
    output_path : "results_n100.txt"

datasets:
    n_nodes : [100] 
    num_graphs_list : [10] 
    graph_idx : [0,9]
    num_samples : 1000
    data_ver : 1

model:
    M : 5
    beta_0 : 0.0001
    beta_1 : 0.02
    T : 1
    hidden_channel : 1
    n_fourier_layers : 10
    norm_type : "batch"
    bias : True

training:
    model_save : True
    epochs : 2000
    batch_size : 1000
    learning_rate : 0.001
    early_stopping_wait : 1000
    T : 0.5
    scheduler: "plateau"
    mmd_model : False
    
evaluation:
    load_order : True
    ordering_option : "order_b_1000"
    ordering_batch_size : 1000
    eval_batch_size : 150
    n_votes : 3
    t_max : 0.1
    masking : True
    residue : True
    pruning_P : False
    cutoff : 0.01
    random_sampling : True

