setup:
    experiment_name : _diffan_n5
    use_wandb : True
    save_folder : 'ckpt'
    output_path : "results_n5.txt"

datasets:
    n_nodes : [5] 
    num_graphs_list : [30] 
    graph_idx : [0,9]
    num_samples : 1000
    data_ver : 1

training:
    model_save : True
    epochs : 1000
    batch_size : 1000
    learning_rate : 0.001
    early_stopping_wait : 1000
    T : 0.5
    scheduler: "plateau"
    mmd_model : False

evaluation:
    load_order : True
    ordering_option : "order_b_1000"
    ordering_batch_size : 1000
    eval_batch_size : 1000
    n_votes : 3
    t_max : 0.1
    masking : True
    residue : True
    pruning_P : False
    cutoff : 0.01
    random_sampling : True

